### ISSUE TITLE
NullReferenceException on Ocell.Tweet

### ISSUE THREAD

**Issue by gjulianm** [gjulianm/Ocell#2]
NullReferenceException
   at Ocell.SPpages.Tweet.SetBindings()
   at Ocell.SPpages.Tweet.Tweet_Loaded(Object sender, RoutedEventArgs e)
   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)

**Comment by gjulianm** [comment]
This error came from StatusConverter, it didn't transfer the Entities property.
