### ISSUE TITLE
Unknown error in Tweet view

### ISSUE THREAD

**Issue by gjulianm** [gjulianm/Ocell#20]
```
NullReferenceException
   at Ocell.Pages.Elements.TweetModel.<CreateCommands>b__b(UserToken item)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ocell.Pages.Elements.TweetModel.<CreateCommands>b__a(Object obj)
   at DanielVaughan.Windows.DelegateCommand`1.CanExecute(T parameter)
   at DanielVaughan.Windows.DelegateCommand`1.CanExecute(Object parameter)
```

**Comment by gjulianm** [comment]
Theoretically it couldn't fail. Closing until further information.
