### ISSUE TITLE
NullReferenceException in GetVisibleItems()

### ISSUE THREAD

**Issue by gjulianm** [gjulianm/Ocell#22]
```
 at Ocell.Controls.ExtendedListBox.GetVisibleItems()
   at Ocell.Controls.ExtendedListBox.SaveInstanceViewport(Object sender, EventArgs e)
   at Ocell.Controls.ExtendedListBox.RaiseSaveViewports()
```

**Comment by gjulianm** [comment]
GetVisibleItems is removed on new version of app.
