### ISSUE TITLE
Error on navigation from Hyperlinks (where?)

### ISSUE THREAD

**Issue by gjulianm** [gjulianm/Ocell#4]
Ocell App Error
Navigation is only supported to relative URIs that are fragments, or begin with '/', or which contain ';component/'.
Parameter name: uri
   at System.Windows.Navigation.NavigationService.Navigate(Uri source)
   at System.Windows.Controls.Frame.Navigate(Uri source)
   at MS.Internal.NavigationHelper.TryInternalNavigate()
   at MS.Internal.NavigationHelper.Navigate(Boolean checkUserInitiatedAction)
   at System.Windows.Controls.HyperlinkButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.Controls.Control.OnMouseLeftButtonUp(Control ctrl, EventArgs e)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)

Sent from my Windows Phone

**Comment by gjulianm** [comment]
The hyperlink button in the user profile. Now corrected.
